/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.buzz.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.buzz.bean.BranchBean;
import com.buzz.exception.CommonException;
import com.buzz.exception.ConnectionException;
import com.buzz.formbean.BranchFormBean;
import com.buzz.serviceimpl.BranchServiceImpl;

public class AddBranchAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BranchFormBean branchFormBean = (BranchFormBean) form;
		BranchBean branchBean = new BranchBean(branchFormBean);
		try {
			new BranchServiceImpl().addBranches(branchBean);
			request.setAttribute("message",
					"Branch Details Inserted SuccessFully");
			return mapping.findForward("success");
		} catch (CommonException e) {
			request.setAttribute("message", e.getMessage());
			return mapping.findForward("fail");
		} catch (Exception e) {
			request.setAttribute("message", "Branch Details  Not Inserted");
			return mapping.findForward("fail");
		}

	}
}