package com.buzz.struts.action;

/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.buzz.bean.BranchBean;
import com.buzz.bean.DiscussionforumBean;
import com.buzz.bean.LogindetailsBean;
import com.buzz.exception.CommonException;
import com.buzz.formbean.DiscussionForumFormBean;
import com.buzz.serviceimpl.BranchServiceImpl;
import com.buzz.serviceimpl.DiscussionForunServiceImpl;

/**
 * MyEclipse Struts Creation date: 07-05-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class AddDiscussionForum extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DiscussionForumFormBean discussionForumFormBean = (DiscussionForumFormBean) form;// TODO
		// Auto-generated
		// method
		// stub
		DiscussionforumBean discussionforumBean = new DiscussionforumBean(
				discussionForumFormBean);
		try {
				HttpSession session = request.getSession();

		/*	discussionforumBean.setEvents(new EventsBean((Integer) session
					.getAttribute("eventid")));*/
			discussionforumBean.setLogindetails(new LogindetailsBean(
					(Integer) session.getAttribute("userid")));
			new DiscussionForunServiceImpl().addFormData(discussionforumBean);
			request.setAttribute("message",
					"Branch Details Inserted SuccessFully");
			return mapping.findForward("success");
		} catch (CommonException e) {
			request.setAttribute("message", e.getMessage());
			return mapping.findForward("fail");
		} catch (Exception e) {
			request.setAttribute("message", "Branch Details  Not Inserted");
			return mapping.findForward("fail");
		}

	}
}