/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.buzz.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.buzz.bean.BranchBean;
import com.buzz.bean.EventsBean;
import com.buzz.exception.CommonException;
import com.buzz.formbean.DiscussionForumFormBean;
import com.buzz.formbean.EventFormBean;
import com.buzz.pojo.Events;
import com.buzz.serviceimpl.BranchServiceImpl;
import com.buzz.serviceimpl.EventServiceImpl;

/**
 * MyEclipse Struts Creation date: 07-27-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/addEvents" name="Events" input="/ADDEvents.jsp"
 *                scope="request" validate="true"
 */
public class AddEventsAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		EventFormBean eventFormBean = (EventFormBean) form;
		EventsBean eventsBean = new EventsBean(eventFormBean);
		try {
			System.out.println("hiiiiiiiii");
			new EventServiceImpl().addEvents(eventsBean);
			request.setAttribute("message",
					"Event Details Inserted SuccessFully");
			return mapping.findForward("success");
		} catch (CommonException e) {
			request.setAttribute("message", e.getMessage());
			return mapping.findForward("fail");
		} catch (Exception e) {
			System.out.println(e);
			request.setAttribute("message", "Events Details  Not Inserted");
			return mapping.findForward("fail");
		}

	}
}