/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.buzz.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.buzz.bean.BranchBean;
import com.buzz.bean.FaqsBean;
import com.buzz.exception.CommonException;
import com.buzz.formbean.FaqsFormBean;
import com.buzz.serviceimpl.BranchServiceImpl;
import com.buzz.serviceimpl.FaqSerivceImpl;

/**
 * MyEclipse Struts Creation date: 07-27-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/addFaq" name="FaqsFormBean" input="/FaqsForm.jsp"
 *                scope="request" validate="true"
 */
public class AddFaqAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		FaqsFormBean FaqsFormBean = (FaqsFormBean) form;// TODO Auto-generated
		// method stub
		FaqsBean faqsBean = new FaqsBean(FaqsFormBean);
		try {
			new FaqSerivceImpl().addFaqs(faqsBean);
			request.setAttribute("message", "Faq  Inserted SuccessFully");
			return mapping.findForward("success");
		} catch (CommonException e) {
			request.setAttribute("message", e.getMessage());
			return mapping.findForward("fail");
		} catch (Exception e) {
			request.setAttribute("message", "Faq   Not Inserted");
			return mapping.findForward("fail");
		}

	}
}