/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.buzz.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.buzz.bean.LogindetailsBean;
import com.buzz.bean.StudentDetailsBean;
import com.buzz.bean.StudydetailsBean;
import com.buzz.exception.CommonException;
import com.buzz.formbean.OrganisedStudentDetailsFormBean;
import com.buzz.formbean.StudentDetailsformBean;
import com.buzz.formbean.StudyDetailsFormBean;
import com.buzz.serviceimpl.StudentDetailsServiceImpl;

/** 
 * MyEclipse Struts
 * Creation date: 07-10-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AddOrganisedStudentAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StudentDetailsformBean studentDetailsformBean = (StudentDetailsformBean) form;
		StudentDetailsBean studentDetailsBean = new StudentDetailsBean(studentDetailsformBean);
		try {
			LogindetailsBean logindetailsBean = new StudentDetailsServiceImpl().organiserRegistration(studentDetailsBean);
			request.setAttribute("message",
					"Organiser Registration SuccessFully");
			request.setAttribute("logindetailsBean", logindetailsBean);
			return mapping.findForward("success");
		} catch (CommonException e) {
			request.setAttribute("message", e.getMessage());
			return mapping.findForward("fail");
		} catch (Exception e) {
			request.setAttribute("message", "Branch Details  Not Inserted");
			return mapping.findForward("fail");
		}
	}
}