/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.buzz.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.buzz.bean.BranchBean;
import com.buzz.bean.GaleryBean;
import com.buzz.exception.CommonException;
import com.buzz.formbean.BranchFormBean;
import com.buzz.formbean.FileUploadForm;
import com.buzz.serviceimpl.BranchServiceImpl;
import com.buzz.serviceimpl.GalleryServiceImpl;

import java.io.*;

public class FileUploadAction extends Action {

	private static final String SUCCESS = "success";
	private static final String FAIL = "fail";
	private FormFile uploadingfile;

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String logicalJspName = FAIL;
		try {
			FileUploadForm fileUploadForm = (FileUploadForm) form;
			uploadingfile = fileUploadForm.getUploadingfile();
			System.out.println(uploadingfile);
			// 1
			String serverPath = getServlet().getServletContext().getRealPath(
					"/")
					+ "upload";
			// 2
			File uploalFolder = new File(serverPath);
			if (!uploalFolder.exists()) {
				uploalFolder.mkdir();
			}
			// 3
			String fileName = uploadingfile.getFileName();
			// 4
			File newFile = new File(serverPath, fileName);
			// 5

			FileOutputStream fos = new FileOutputStream(newFile);

			// 6
			fos.write(uploadingfile.getFileData());

			// 7

			fos.flush();
			fos.close();

			// 8
			request.setAttribute("downloadLocation", "./upload/" + fileName);
			System.out.println(request.getAttribute("downloadLocation"));
			logicalJspName = SUCCESS;
			GaleryBean galeryBean = new GaleryBean();
			galeryBean.setGaleryfile1(uploadingfile.getFileData());
			try {
				String[] aString = fileName.split("\\.");
				galeryBean.setFaleryfileextension(aString[1]);
			} catch (Exception e) {
				// TODO: handle exception
			}

			try {
				new GalleryServiceImpl().addGaleryFile(galeryBean);
				request.setAttribute("message", "Galery File Uploaded");
				return mapping.findForward("success");
			} catch (CommonException e) {
				request.setAttribute("message", e.getMessage());
				return mapping.findForward("fail");
			} catch (Exception e) {
				request.setAttribute("message", "Galery Not File Uploaded");
				return mapping.findForward("fail");
			}
		} catch (Exception e) {
			request.setAttribute("message", "Galery Not File Uploaded");
			return mapping.findForward("fail");
		}
	}
}