/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.buzz.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.buzz.bean.LogindetailsBean;
import com.buzz.formbean.LogindetailsFormbean;
import com.buzz.serviceimpl.SecurityServiceImpl;

/**
 * MyEclipse Struts Creation date: 07-27-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/login" name="LogindetailsFormbean"
 *                input="/LoginForm.jsp" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LogindetailsFormbean logindetailsFormbean = (LogindetailsFormbean) form;// TODO
		// Auto-generated
		// method
		// stub
		LogindetailsBean logindetailsBean = new LogindetailsBean(
				logindetailsFormbean);
		HttpSession session = request.getSession();
		LogindetailsBean logindetailsBean2;
		try {
			logindetailsBean2 = new SecurityServiceImpl()
					.loginCheck(logindetailsBean);
			if (!logindetailsBean.equals(null)) {
				session.setAttribute("loginid", logindetailsBean2.getLoginid());
				session.setAttribute("userid", logindetailsBean2.getUserid());
				session.setAttribute("logintype", logindetailsBean2
						.getLogintype());
					
				request.setAttribute("message", "WELCOME");
				/*
				 * System.out.println(session.getAttribute("loginid"));
				 * System.out.println(session.getAttribute("logintype"));
				 * System.out.println(session.getAttribute("branchid"));
				 * System.out.println(session.getAttribute("eventid"));
				 * System.out.println(session.getAttribute("studentname"));
				 * System.out.println(session.getAttribute("collegename"));
				 */
				return mapping.findForward("success");
			} else {
				request.setAttribute("message", "Invalid loginid and password");
				return mapping.findForward("fail");
			}
		} catch (Exception e) {
			request.setAttribute("message", e.getMessage());
			return mapping.findForward("fail");
		}
	}
}