/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.buzz.struts.action;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.buzz.bean.BranchBean;
import com.buzz.exception.CommonException;
import com.buzz.formbean.BranchFormBean;
import com.buzz.serviceimpl.BranchServiceImpl;

/**
 * MyEclipse Struts Creation date: 07-08-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/ViewBranches.jsp"
 */
public class UpdateBranchAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BranchFormBean branchFormBean = (BranchFormBean) form;
		BranchBean branchBean = new BranchBean(branchFormBean);
		String target = null;
		Vector<BranchBean> vBranchBeans = null;
		try {
			branchBean.setBranchid(Integer.parseInt(request
					.getParameter("branchid")));
			boolean flag = new BranchServiceImpl().branhcUpdatebyid(branchBean);
			vBranchBeans = new BranchServiceImpl().viewBranches();
			if (flag && !vBranchBeans.isEmpty()) {
				request.setAttribute("vBranchBeans", vBranchBeans);
				target = "success";
			} else {
				target = "failure";
			}
		} catch (CommonException e) {
			// message = new ActionMessage(e.getMessage());
			request.setAttribute("message", e.getMessage());
			target = "failure";
		} catch (Exception e) {
			request.setAttribute("message", "Data Not Updated");
			target = "failure";
		}
		return mapping.findForward(target);

	}
}