/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.buzz.struts.action;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.buzz.bean.BranchBean;
import com.buzz.exception.CommonException;
import com.buzz.formbean.BranchFormBean;
import com.buzz.serviceimpl.BranchServiceImpl;

/**
 * MyEclipse Struts Creation date: 07-08-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/ViewBranchByid.jsp"
 */
public class ViewBranchByidAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BranchBean branchBean = null;
		String target = null;
		try {
			branchBean = new BranchServiceImpl().viewBranchbyId(Integer
					.parseInt(request.getParameter("branchid")));
			if (!branchBean.equals(null)) {
				request.setAttribute("branchBean", branchBean);
				target = "success";
			} else {
				target = "failure";
			}
		} catch (CommonException e) {
			// message = new ActionMessage(e.getMessage());
			request.setAttribute("message", e.getMessage());
			target = "failure";
		} catch (Exception e) {

			request.setAttribute("message", "No Branch Data");
			target = "failure";
		}
		return mapping.findForward(target);

	}
}